// ESLint 9 flat config.
const expoConfig = require('eslint-config-expo/flat');
const prettier = require('eslint-plugin-prettier');
const prettierConfig = require('eslint-config-prettier');

module.exports = [
  ...expoConfig,
  prettierConfig,
  {
    plugins: { prettier },
    rules: {
      'prettier/prettier': 'warn',
      // The design-token rule: components read colour from useTheme(), never
      // from a literal. Enforced by review; kept here as a reminder anchor.
      'no-restricted-syntax': [
        'warn',
        {
          selector: 'Literal[value=/^#[0-9a-fA-F]{3,8}$/]',
          message:
            'Hex colours belong in src/theme/tokens.ts (README § Design Tokens), not in components.',
        },
      ],
    },
  },
  {
    // The theme is where the hex values are supposed to live.
    files: ['src/theme/**/*.ts'],
    rules: { 'no-restricted-syntax': 'off' },
  },
  {
    // The acceptance-test scripts and the build helpers run under Node, not
    // React Native, so the Node globals are legitimate there.
    files: ['tests/**/*.mjs', 'scripts/**/*.mjs'],
    languageOptions: {
      globals: { Buffer: 'readonly', process: 'readonly', console: 'readonly' },
    },
  },
  {
    ignores: [
      'node_modules/**',
      '.expo/**',
      'dist/**',
      'web-build/**',
      'supabase/**',
      'support.js',
      'ios-frame.jsx',
      // Generated by expo-cli on every start.
      'expo-env.d.ts',
    ],
  },
];
